export function isJobEmail(subject: string, from: string, snippet: string): boolean {
  const jobKeywords = [
    'thank you for applying',
    'we received your application',
    'interview',
    'position',
    'resume',
    'career',
    'job',
    'opportunity',
    'offer',
    'application',
    'candidate',
    'hiring',
    'recruiter',
    'recruitment',
    'talent acquisition',
    'cv',
    'curriculum vitae',
    'shortlisted',
    'selected',
    'not selected',
    'regret to inform',
    'move forward',
    'next steps',
    'assessment',
    'screening',
    'background check',
    'reference check',
    'job posting',
    'job opening',
    'vacancy',
    'job alert',
    'job match',
    'job search',
    'job seeker',
    'apply now',
    'application received',
    'application status',
    'application update',
    'application process',
    'application submitted',
    'application under review',
    'application confirmation',
    'application acknowledgement',
    'application unsuccessful',
    'application successful',
    'application complete',
    'application incomplete',
    'job description',
    'job details',
    'job requirements',
    'job responsibilities',
    'job duties',
    'job title',
    'job location',
    'job type',
    'job reference',
    'job id',
    'job code',
    'job posting',
    'job vacancy',
    'job opportunity',
    'job offer',
    'employment',
    'employment opportunity',
    'employment offer',
    'employment application',
    'employment status',
    'employment verification',
    'employment history',
    'employment details',
    'employment confirmation',
    'employment contract',
    'employment agreement',
    'onboarding',
    'welcome to the team',
    'start date',
    'joining date',
    'orientation',
    'congratulations',
    'successful candidate',
    'unsuccessful candidate',
  ];

  const body = `${subject} ${from} ${snippet}`.toLowerCase();
  return jobKeywords.some(keyword => body.includes(keyword));
}
